### ISSUE TITLE
Failed to Support for Remote Control and Now Playing Information

### ISSUE THREAD

**Issue by DiER-WANG** [Alterplay/APAudioPlayer#12]
Is it can support for Remote Control and Now Playing Information ? I tried but failed

**Comment by reejosamuel** [comment]
Tried the same failed, I don't think the audio output channel BASS library is the same iOS uses to detect if audio is being played back. And if iOS doesn't detect audio play back then it doesn't show the now playing info is what i read from various sources on the internet

**Comment by DiER-WANG** [comment]
oh, Thank you very much for answer the question
