### ISSUE TITLE
bass_fx

### ISSUE THREAD

**Issue by trirejeki89** [Alterplay/APAudioPlayer#3]
can you add add-on bass_fx to the project also?

**Comment by Krivoblotsky** [comment]
APAudioPlayer doesn't use bass_fx in current implementation. What do you need it for? For kind of feature do you expect?

**Comment by trirejeki89** [comment]
i need to use FX function on bass.h such as BASS_DX8_I3DL2REVERB, to modify audio reverb filter, such as level of audio / decay of audio.

**Comment by Krivoblotsky** [comment]
Do you want to use it with APAudioPlayer, or you just want to interact with BASS directly?

**Comment by trirejeki89** [comment]
i want to use it with APAudioPlayer, it really good lib and easy to use :smile:

**Comment by Krivoblotsky** [comment]
Ok, I'll schedule you request for the next release.

**Comment by trirejeki89** [comment]
okay, thank you.

**Comment by pgorasva** [comment]
@Krivoblotsky 

any update for bass_fx ?

**Comment by pgorasva** [comment]
@trirejeki89 

is there any update for bass_fx  ?
