### ISSUE TITLE
Getting Current Time of Audio

### ISSUE THREAD

**Issue by imuhammadjabbar** [Alterplay/APAudioPlayer#5]
Is there a way to get current time of currently playing audio? I did not find any of this functionality.
Don't you think? There should be a way to get current time of audio. 

please see attachment for more Clearance.

Thanks.

![currenttime](https://cloud.githubusercontent.com/assets/12771786/9576349/57e98170-4ff0-11e5-8d0d-31be905b8e09.png)

**Comment by Krivoblotsky** [comment]
You can do it even with current implementation.

APAudioPlayer has total track duration in seconds and current progress

``` objc
- (NSTimeInterval)duration;

@property (nonatomic, assign) CGFloat position;
```

So the current position in seconds will be duration \* position.

**Comment by imuhammadjabbar** [comment]
Yes, got it.

Thanks a lot...
