### ISSUE TITLE
cannot play .mp2 file?

### ISSUE THREAD

**Issue by xjcristal** [Alterplay/APAudioPlayer#9]
I  have loaded a .mp2 file in the project, and changed the url such as the picture1 below
![1](https://cloud.githubusercontent.com/assets/11403491/10867986/549e9988-80ba-11e5-9058-21ab03b48f1f.png)

,but then the project crash such as picture2 below 
![2](https://cloud.githubusercontent.com/assets/11403491/10867989/7b23f314-80ba-11e5-9332-e57a62c9f529.png)

**Comment by xjcristal** [comment]
how can i solve the problem above?  maybe i'm wrong at somewhere? helping your answer. Thanks~

**Comment by xjcristal** [comment]
I've found where  my problem exists ..ignore my question please!! so sorry to trouble you.

**Comment by Krivoblotsky** [comment]
No problem.
